version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  datavolume: